version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: wortise-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: wortise

volumes:
  mongo_data: